# Generated by Django 5.2.5 on 2025-09-06 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва залу')),
                ('address', models.CharField(max_length=255, verbose_name='Адреса')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вмістимість')),
            ],
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Ім'я виконавця/групи")),
                ('genre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Жанр')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва концерту')),
                ('date', models.DateTimeField(verbose_name='Дата та час')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concerts', to='app.hall')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concerts', to='app.performer')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=5, verbose_name='Ряд')),
                ('number', models.PositiveIntegerField(verbose_name='Номер місця')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='app.hall')),
            ],
            options={
                'unique_together': {('hall', 'row', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна')),
                ('is_reserved', models.BooleanField(default=False, verbose_name='Заброньований')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='app.concert')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='app.seat')),
            ],
            options={
                'unique_together': {('concert', 'seat')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата бронювання')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='app.ticket')),
            ],
        ),
    ]
